[package]
name = "cfg_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.8.0"
iced-x86 = "1.21.0"
dot2 = "1.0.0"
petgraph = "0.6.4"
